Release 2.6-7.4.0 - See CHANGELOG.md

diff --git a/install/etc/services.available/20-openldap-backup/run b/install/etc/services.available/20-openldap-backup/run
--- a/install/etc/services.available/20-openldap-backup/run
+++ b/install/etc/services.available/20-openldap-backup/run
@@ -7,13 +7,7 @@ check_container_initialized
 check_service_initialized init 10-openldap
 liftoff
 
-date >/dev/null
-
-if [ "$1" != "NOW" ]; then
-    sleep 10
-fi
-
-if [ "$BACKUP_LOCATION" = "S3" ] || [ "$BACKUP_LOCATION" = "s3" ] || [ "$BACKUP_LOCATION" = "MINIO" ] || [ "$BACKUP_LOCATION" = "minio" ] ; then
+if [ "${BACKUP_LOCATION}" = "s3" ] || [ "${BACKUP_LOCATION}" = "minio" ]; then
     S3_PROTOCOL=${S3_PROTOCOL:-"https"}
     sanity_var S3_BUCKET "S3 Bucket"
     sanity_var S3_KEY_ID "S3 Key ID"
@@ -24,14 +18,8 @@ if [ "$BACKUP_LOCATION" = "S3" ] || [ "$BACKUP_LOCATION" = "s3" ] || [ "$BACKUP_
     file_env 'S3_KEY_SECRET'
 fi
 
-
-if [ "$1" = "NOW" ]; then
-    BACKUP_BEGIN=+0
-    MANUAL=TRUE
-fi
-
 ### Set Compression Options
-if var_true "${BACKUP_PARALLEL_COMPRESSION}" ; then
+if var_true "${BACKUP_PARALLEL_COMPRESSION}"; then
     bzip="pbzip2 -${BACKUP_COMPRESSION_LEVEL}"
     gzip="pigz -${BACKUP_COMPRESSION_LEVEL}"
     xzip="pixz -${BACKUP_COMPRESSION_LEVEL}"
@@ -44,167 +32,213 @@ else
 fi
 
 backup_openldap() {
-    # Schemas
     print_notice "Backing up configuration schemas"
-    target=${now}_openldap_config
-    compression
-    /usr/sbin/slapcat -F "${CONFIG_PATH}"/slapd.d -n 0 | $dumpoutput > ${BACKUP_TEMP_LOCATION}/"${target}"
-    generate_md5
-    move_backup
-    # Data
+    target=config
+    /usr/sbin/slapcat -F "${CONFIG_PATH}"/slapd.d -n 0  > "${BACKUP_TEMP_LOCATION}"/"${target}"
+    exit_code=$?
+    check_exit_code $target
     print_notice "Backing up user data"
-    target=${now}_openldap_data
+    target=data
+    /usr/sbin/slapcat -F "${CONFIG_PATH}"/slapd.d -n 1 > "${BACKUP_TEMP_LOCATION}"/"${target}"
+    exit_code=$?
+    check_exit_code $target
+    target=${now}-openldap_${CONTAINER_NAME}
     compression
-    /usr/sbin/slapcat -F "${CONFIG_PATH}"/slapd.d -n 1 | $dumpoutput > ${BACKUP_TEMP_LOCATION}/"${target}"
-    generate_md5
+    generate_checksum
     move_backup
 }
 
-compression() {
-   case "${BACKUP_COMPRESSION,,}" in
-        "bz" | "bzip2" | "bzip" | "bz2" )
-            print_notice "Compressing backup with bzip2"
-            target=${target}.bz2
-            dumpoutput="$bzip "
+check_exit_code() {
+    print_debug "OpenLDAP Backup Exit Code is ${exit_code}"
+    case "${exit_code}" in
+    0)
+        print_info "OpenLDAP Backup of '${1}' completed successfully"
         ;;
-        "gz" | "gzip" )
-            print_notice "Compressing backup with gzip"
-            target=${target}.gz
-            dumpoutput="$gzip "
-        ;;
-        "none" | "false")
-            dumpoutput="cat "
-        ;;
-        "xz" | "xzip" )
-            print_notice "Compressing backup with xzip"
-            target=${target}.xz
-            dumpoutput="$xzip "
-        ;;
-        "zstd" | "zst" )
-            print_notice "Compressing backup with zstd"
-            target=${target}.zst
-            dumpoutput="$zstd "
+    *)
+        print_error "OpenLDAP Backup of '${1}' reported errors"
+        master_exit_code=1
         ;;
     esac
 }
 
-generate_md5() {
-    if var_true "${BACKUP_MD5}" ; then
-        print_notice "Generating MD5 for ${target}"
-        cd "${BACKUP_TEMP_LOCATION}"
-        md5sum "${target}" > "${target}".md5
-        MD5VALUE=$(md5sum "${target}" | awk '{ print $1}')
+compression() {
+    case "${BACKUP_COMPRESSION,,}" in
+    bz*)
+        print_notice "Compressing backup with bzip2"
+        target=${target}.bz2
+        tar --use-compress-program="${bzip} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data
+        ;;
+    gz*)
+        print_notice "Compressing backup with gzip"
+        target=${target}.gz
+        tar --use-compress-program="${gzip} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data
+        ;;
+    "none" | "false")
+        tar -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data
+        ;;
+    xz*)
+        print_notice "Compressing backup with xzip"
+        target=${target}.xz
+        tar --use-compress-program="${xzip} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data
+        ;;
+    zst*)
+        print_notice "Compressing backup with zstd"
+        target=${target}.zst
+        tar --use-compress-program="${zstd} " -cf "${BACKUP_TEMP_LOCATION}"/"${target}" -C "${BACKUP_TEMP_LOCATION}" config data
+        ;;
+    esac
+}
+
+generate_checksum() {
+    if var_true "${BACKUP_ENABLE_CHECKSUM}"; then
+        if [ "${exit_code}" = "0" ]; then
+            case "${BACKUP_CHECKSUM,,}" in
+            "md5")
+                checksum_command="md5sum"
+                checksum_extension="md5"
+                ;;
+            sha*)
+                checksum_command="sha1sum"
+                checksum_extension="sha1"
+                ;;
+            esac
+
+            print_notice "Generating ${checksum_extension^^} for '${target}'"
+            cd "${BACKUP_TEMP_LOCATION}"
+            ${checksum_command} "${target}" >"${target}"."${checksum_extension}"
+            checksum_value=$(${checksum_command} "${target}" | awk ' { print $1}')
+            print_debug "${checksum_extension^^}: ${checksum_value} - ${target}"
+        else
+            print_error "Skipping Checksum creation because backup did not complete successfully"
+        fi
     fi
 }
 
 move_backup() {
     case "${BACKUP_SIZE_VALUE,,}" in
-        "b" | "bytes" )
-            BACKUP_SIZE_VALUE=1
+    "b" | "bytes")
+        BACKUP_SIZE_VALUE=1
         ;;
-        "[kK]" | "[kK][bB]" | "kilobytes" | "[mM]" | "[mM][bB]" | "megabytes" )
-            BACKUP_SIZE_VALUE="-h"
+    "[kK]" | "[kK][bB]" | "kilobytes" | "[mM]" | "[mM][bB]" | "megabytes")
+        BACKUP_SIZE_VALUE="-h"
         ;;
-        *)
-            BACKUP_SIZE_VALUE=1
+    *)
+        BACKUP_SIZE_VALUE=1
         ;;
     esac
-    if [ "$BACKUP_SIZE_VALUE" = "1" ] ; then
-        FILESIZE=$(stat -c%s "${BACKUP_TEMP_LOCATION}/${target}")
+    if [ "$BACKUP_SIZE_VALUE" = "1" ]; then
+        FILESIZE="$(stat -c%s "${BACKUP_TEMP_LOCATION}"/"${target}")"
         print_notice "Backup of ${target} created with the size of ${FILESIZE} bytes"
     else
-        FILESIZE=$(du -h "${BACKUP_TEMP_LOCATION}/${target}" | awk '{ print $1}')
+        FILESIZE=$(du -h "${BACKUP_TEMP_LOCATION}"/"${target}" | awk '{ print $1}')
         print_notice "Backup of ${target} created with the size of ${FILESIZE}"
     fi
 
     case "${BACKUP_TYPE,,}" in
-        "file" | "filesystem" )
+        file* )
             mkdir -p "${BACKUP_PATH}"
-            mv "${BACKUP_TEMP_LOCATION}"/*.md5 "${BACKUP_PATH}"/
+            silent mv "${BACKUP_TEMP_LOCATION}"/*."${checksum_extension}" "${BACKUP_PATH}"/
             mv "${BACKUP_TEMP_LOCATION}"/"${target}" "${BACKUP_PATH}"/"${target}"
+            if var_true "${BACKUP_CREATE_LATEST_SYMLINK}"; then
+                ln -sf "${BACKUP_PATH}"/"${target}" "${BACKUP_PATH}"/latest-openldap_"${CONTAINER_NAME}"
+            fi
+            if [ -n "${BACKUP_ARCHIVE_TIME}" ]; then
+                mkdir -p "${BACKUP_PATH_ARCHIVE}"
+                find "${BACKUP_PATH}"/ -maxdepth 1 -mmin +"${BACKUP_ARCHIVE_TIME}" -iname "*" -exec mv {} "${BACKUP_PATH_ARCHIVE}" \;
+            fi
         ;;
-        "s3" | "minio" )
+        "s3" | "minio")
             export AWS_ACCESS_KEY_ID=${S3_KEY_ID}
             export AWS_SECRET_ACCESS_KEY=${S3_KEY_SECRET}
             export AWS_DEFAULT_REGION=${S3_REGION}
 
-            [[ ( -n "${S3_HOST}" ) ]] && PARAM_AWS_ENDPOINT_URL=" --endpoint-url ${S3_PROTOCOL}://${S3_HOST}"
+            [[ (-n "${S3_HOST}") ]] && PARAM_AWS_ENDPOINT_URL=" --endpoint-url ${S3_PROTOCOL}://${S3_HOST}"
 
             aws ${PARAM_AWS_ENDPOINT_URL} s3 cp ${TEMP_LOCATION}/${target} s3://${S3_BUCKET}/${S3_PATH}/${target}
 
-            rm -rf "${BACKUP_TEMP_LOCATION}"/*.md5
+            silent rm -rf "${BACKUP_TEMP_LOCATION}"/"${checksum_extension}"
             rm -rf "${BACKUP_TEMP_LOCATION}"/"${target}"
         ;;
     esac
+            rm -rf "${BACKUP_TEMP_LOCATION}"/config
+            rm -rf "${BACKUP_TEMP_LOCATION}"/data
 }
 
-###
-### Container Startup
-print_debug "Backup routines Initialized on $(date)"
-
-### Wait for Next time to start backup
-if [ "$1" != "NOW" ]; then
+if [ "${MODE,,}" = "manual" ] || [ "${1,,}" = "manual" ] || [ "${1,,}" = "now" ]; then
+    sleep 1
+    BACKUP_BEGIN=+0
+    manual=TRUE
+    print_debug "Detected Manual Mode"
+else
+    sleep 5
     current_time=$(date +"%s")
     today=$(date +"%Y%m%d")
 
     if [[ $BACKUP_BEGIN =~ ^\+(.*)$ ]]; then
-        waittime=$(( ${BASH_REMATCH[1]} * 60 ))
+        waittime=$((${BASH_REMATCH[1]} * 60))
         target_time=$(($current_time + $waittime))
     else
-        target_time=$(date --date="${today} ${BACKUP_BEGIN}" +"%s")
+        target_time=$(date --date="${today}${BACKUP_BEGIN}" +"%s")
         if [[ "$target_time" < "$current_time" ]]; then
-            target_time=$(($target_time + 24*60*60))
+            target_time=$(($target_time + 24 * 60 * 60))
         fi
         waittime=$(($target_time - $current_time))
     fi
 
+    print_debug "Wait Time: ${waittime} Target time: ${target_time} Current Time: ${current_time}"
     print_notice "Next Backup at $(date -d @${target_time} +"%Y-%m-%d %T %Z")"
     sleep $waittime
 fi
 
 ### Commence Backup
-  while true; do
-    # make sure the directory exists
-    mkdir -p ${BACKUP_TEMP_LOCATION}
+while true; do
+    mkdir -p "${BACKUP_TEMP_LOCATION}"
+    backup_start_time=$(date +"%s")
+    print_debug "Backup routines started time: $(date +'%Y-%m-%d %T %Z')"
     now=$(date +"%Y%m%d-%H%M%S")
     now_time=$(date +"%H:%M:%S")
     now_date=$(date +"%Y-%m-%d")
     backup_openldap
+    backup_finish_time=$(date +"%s")
+    backup_total_time=$(echo $((backup_finish_time - backup_start_time)))
+    if [ -z "$master_exit_code" ]; then master_exit_code="0"; fi
+    print_info "Backup routines finish time: $(date -d @${backup_finish_time} +"%Y-%m-%d %T %Z") with overall exit code ${master_exit_code}"
+    print_notice "Backup routines time taken: $(echo ${backup_total_time} | awk '{printf "Hours: %d Minutes: %02d Seconds: %02d", $1/3600, ($1/60)%60, $1%60}')"
 
-### Zabbix
-    if var_true "${CONTAINER_ENABLE_MONITORING}" ; then
+    ### Zabbix
+    if var_true "${CONTAINER_ENABLE_MONITORING}"; then
         print_notice "Sending Backup Statistics to Zabbix"
-        silent zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k dbbackup.size -o $(stat -c%s "${BACKUP_PATH}"/"${target}")
-        silent zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k dbbackup.datetime -o $(date -r  "${BACKUP_PATH}"/"${target}" +'%s')
+        silent zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k openldap.backup.size -o "$(stat -c%s "${BACKUP_PATH}"/"${target}")"
+        silent zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -k openldap.backup.datetime -o "$(date -r "${BACKUP_PATH}"/"${target}" +'%s')"
     fi
 
-### Automatic Cleanup
-    if [[ -n "$BACKUP_RETENTION" ]]; then
+    ### Automatic Cleanup
+    if [[ -n "${BACKUP_RETENTION}" ]]; then
         print_notice "Cleaning up old backups"
-        find "$BACKUP_PATH"/  -mmin +"$BACKUP_RETENTION" -iname "*" -exec rm {} \;
+        find "${BACKUP_PATH}"/ -mmin +"${BACKUP_RETENTION}" -iname "*" -exec rm {} \;
     fi
 
-    if [ -n "$POST_SCRIPT" ] ; then
+    ### Post Backup Custom Script Support
+    if [ -n "${POST_SCRIPT}" ]; then
         print_notice "Found POST_SCRIPT environment variable. Executing"
         eval "${POST_SCRIPT}"
     fi
 
-### Post Backup Custom Script Support
-    if [ -d /assets/custom-backup-scripts/ ] ; then
-    print_notice "Found Custom Scripts to Execute"
-    for f in $(find /assets/custom-backup-scripts/ -name \*.sh -type f); do
-      print_notice "Running Script ${f}"
-      ## script DATE TIME BACKUP_FILENAME FILESIZE MD5_VALUE
-      ${f} "${now_date}" "${now_time}" "${target}" "${FILESIZE}" "${MD5VALUE}"
-    done
+    if [ -d /assets/custom-backup-scripts/ ]; then
+        print_notice "Found Custom Scripts to Execute"
+        for f in $(find /assets/custom-backup-scripts/ -name \*.sh -type f); do
+            print_notice "Running Script ${f}"
+            ## script DATE TIME BACKUP_FILENAME FILESIZE CHECKSUM VALUE
+            ${f} "${now_date}" "${now_time}" "${target}" "${FILESIZE}" ${checksum_value}
+        done
     fi
 
     ### Go back to Sleep until next Backup time
-    if var_true $MANUAL ; then
-        exit 0;
+    if var_true "${manual}"; then
+        print_debug "Exiting due to manual mode"
+        exit ${master_exit_code}
     else
-        sleep $(($BACKUP_INTERVAL*60))
+        print_notice "Sleeping for another $(($BACKUP_INTERVAL * 60 - backup_total_time)) seconds. Waking up at $(date -d@"$(($(date +%s) + $(($BACKUP_INTERVAL * 60 - backup_total_time))))" +"%Y-%m-%d %T %Z") "
+        sleep $(($BACKUP_INTERVAL * 60 - backup_total_time))
     fi
-
-  done
-fi
+done
